export const ROUTES = {
    HOME: '@EXAMPLE/HOME',
    OTHER: '@EXAMPLE/OTHER',
    SIGN_IN: '@EXAMPLE/SIGN_IN',
    REGISTER: '@EXAMPLE/REGISTER',
    VERIFY: '@EXAMPLE/VERIFY',
    CREATE_ACCOUNT: '@EXAMPLE/CREATE_ACCOUNT',
    FORGOT: '@EXAMPLE/FORGOT',
    RESET_PASSWORD: '@EXAMPLE/RESET_PASSWORD',
    AUTH_LOADING: '@EXAMPLE/AUTH_LOADING',
    APP: '@EXAMPLE/APP',
    AUTH: '@EXAMPLE/AUTH',
}