export const ROUTES = {
    APP_GROUP: 'APP_GROUP' as const,
    // AUTH_GROUP: '@ROUTE_GROUP/AUTH',
    // MAIN_GROUP: '@ROUTES_GROUP/MAIN',

    // LESSONS_GROUP: '@ROUTES_GROUP/LESSONS',
    // HOME_GROUP: '@ROUTES_GROUP/HOME',
    // TIPS_GROUP: '@ROUTES_GROUP/TIPS',
    // BLOGS_GROUP: '@ROUTES_GROUP/BLOGS',
    SUBMIT_GROUP: 'SUBMIT_GROUP' as const,
    SETTINGS_GROUP: 'SETTINGS_GROUP' as const,
    // ABOUT_GROUP: '@ROUTES_GROUP/ABOUT',
    // FAQ_GROUP: '@ROUTES_GROUP/FAQ',
    // ORDER_GROUP: '@ROUTES_GROUP/ORDER',

    // LESSONS_GROUP: '@ROUTES_GROUP/LESSONS'
    // APP: '@ROUTE_GROUP/APP',

    ABOUT: 'ABOUT' as const,
    // AUTH_LOADING: 'AUTH_LOADING',
    ACCOUNT_DETAILS: 'ACCOUNT' as const,
    BLOGS: 'BLOGS' as const,
    BLOG: 'BLOG' as const,
    CONTACT: 'CONTACT' as const,
    FAQ: 'FAQ' as const,
    HOME: 'HOME' as const,
    HISTORY: 'HISTORY' as const,
    LESSONS: 'LESSONS' as const,
    LESSON: 'LESSON' as const,
    LOGIN: 'LOGIN' as const,
    LOGS: 'LOGS' as const,
    ORDER: 'ORDER' as const,
    PROS: 'PROS' as const,
    RECORD: 'RECORD' as const,
    SUBMIT: 'SUBMIT' as const,
    REGISTER: 'REGISTER' as const,
    RESET_PASSWORD: 'RESET_PASSWORD' as const,
    SETTINGS: 'SETTINGS' as const,
    SETTING: 'SETTING' as const,
    TIPS: 'TIPS' as const,
    TIP: 'TIP' as const,
};
