export const ROUTES = {
    APP_GROUP: 'APP_GROUP' as const,
    SUBMIT_GROUP: 'SUBMIT_GROUP' as const,
    SETTINGS_GROUP: 'SETTINGS_GROUP' as const,
    ABOUT: 'ABOUT' as const,
    ACCOUNT_DETAILS: 'ACCOUNT' as const,
    BLOGS: 'BLOGS' as const,
    BLOG: 'BLOG' as const,
    CONTACT: 'CONTACT' as const,
    FAQ: 'FAQ' as const,
    HOME: 'HOME' as const,
    HISTORY: 'HISTORY' as const,
    LESSONS: 'LESSONS' as const,
    LESSON: 'LESSON' as const,
    LOGIN: 'LOGIN' as const,
    LOGS: 'LOGS' as const,
    ORDER: 'ORDER' as const,
    PROS: 'PROS' as const,
    RECORD: 'RECORD' as const,
    SUBMIT: 'SUBMIT' as const,
    REGISTER: 'REGISTER' as const,
    RESET_PASSWORD: 'RESET_PASSWORD' as const,
    SETTINGS: 'SETTINGS' as const,
    SETTING: 'SETTING' as const,
    TIPS: 'TIPS' as const,
    TIP: 'TIP' as const,
};
